# A simple coin toss game. The goal of the game is
# to toss coin 100 times and calculate how many
# heads or tails.

# import the random generator library
import random

# for this program, zero is a head and 1 is a tail.
# we need to keep track of number of 0's and 1's
# generated by the random library

heads = 0 # a counter to count heads or tails

# Change the value of MAX variable and to play around

MAX = 100 # number of times we want to toss the coin

# for loop will run from 1 to MAX value set above
for i in range(1,MAX):
    toss = random.randint(0,1) # generate 0 or a 1
    if (toss == 0): # if zero, it's heads
        heads = heads+1 # increment heads by 1

print("Heads: ", heads) # print heads
print("Tails: ", MAX - heads)  # print tails, total - heads
print("Total: ", MAX)  # print total


